/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.proway.exemplos.orientacao.objetos.telas;

import javax.swing.table.DefaultTableModel;

public class PessoaJFrame extends javax.swing.JFrame {

    // Instanciado um objeto da classe PessoaServico que permitirá gerenciar 
    // os registros das pessoas
    private PessoaServico pessoaServico = new PessoaServico();
    
    /**
     * Creates new form PessoaJFrame
     */
    public PessoaJFrame() {
        initComponents();
        
        habilitarModoCadastroRapido();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipoCadastro = new javax.swing.ButtonGroup();
        jLabelCadastroRapidoNome = new javax.swing.JLabel();
        jTextFieldCadastroRapidoNome = new javax.swing.JTextField();
        jRadioButtonCadastroRapido = new javax.swing.JRadioButton();
        jRadioButtonCadastroCompleto = new javax.swing.JRadioButton();
        jLabelCadastroRapidoRenda = new javax.swing.JLabel();
        jTextFieldCadastroRapidoRenda = new javax.swing.JTextField();
        jButtonCadastroRapidoSalvar = new javax.swing.JButton();
        jLabelCadastroCompletoNome = new javax.swing.JLabel();
        jTextFieldCadastroCompletoNome = new javax.swing.JTextField();
        jLabelCadastroCompletoCpf = new javax.swing.JLabel();
        jFormattedTextFieldCadastroCompletoCpf = new javax.swing.JFormattedTextField();
        jLabelCadastroCompletoSigno = new javax.swing.JLabel();
        jComboBoxCadastroCompletoSigno = new javax.swing.JComboBox<>();
        jLabelCadastroCompletoRenda = new javax.swing.JLabel();
        jTextFieldCadastroCompletoRenda = new javax.swing.JTextField();
        jCheckBoxCadastroCompletoTemPet = new javax.swing.JCheckBox();
        jButtonCadastroCompletoSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelCadastroRapidoNome.setText("Nome");

        buttonGroupTipoCadastro.add(jRadioButtonCadastroRapido);
        jRadioButtonCadastroRapido.setSelected(true);
        jRadioButtonCadastroRapido.setText("Cadastro rápido");
        jRadioButtonCadastroRapido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCadastroRapidoActionPerformed(evt);
            }
        });

        buttonGroupTipoCadastro.add(jRadioButtonCadastroCompleto);
        jRadioButtonCadastroCompleto.setText("Cadastro completo");
        jRadioButtonCadastroCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCadastroCompletoActionPerformed(evt);
            }
        });

        jLabelCadastroRapidoRenda.setText("Renda");

        jButtonCadastroRapidoSalvar.setText("Salvar");
        jButtonCadastroRapidoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroRapidoSalvarActionPerformed(evt);
            }
        });

        jLabelCadastroCompletoNome.setText("Nome");

        jLabelCadastroCompletoCpf.setText("CPF");

        try {
            jFormattedTextFieldCadastroCompletoCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabelCadastroCompletoSigno.setText("Signo");

        jComboBoxCadastroCompletoSigno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Áries", "Touro", "Gêmeos", "Câncer", "Leão", "Virgem", "Libra", "Escorpião", "Sagitário", "Capricórnio", "Aquário", "Peixes" }));

        jLabelCadastroCompletoRenda.setText("Renda");

        jCheckBoxCadastroCompletoTemPet.setText("Tem pet?");

        jButtonCadastroCompletoSalvar.setText("Salvar");
        jButtonCadastroCompletoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroCompletoSalvarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "Renda", "PET", "Signo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Boolean.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(jRadioButtonCadastroRapido, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelCadastroRapidoNome))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCadastroRapidoRenda)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextFieldCadastroRapidoRenda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                        .addComponent(jTextFieldCadastroRapidoNome, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jButtonCadastroRapidoSalvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(200, 200, 200)
                                .addComponent(jTextFieldCadastroCompletoRenda))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelCadastroCompletoNome, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButtonCadastroCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelCadastroCompletoSigno)
                                        .addGap(173, 173, 173)
                                        .addComponent(jLabelCadastroCompletoRenda)))
                                .addGap(0, 91, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jCheckBoxCadastroCompletoTemPet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxCadastroCompletoSigno, javax.swing.GroupLayout.Alignment.LEADING, 0, 164, Short.MAX_VALUE)
                                    .addComponent(jTextFieldCadastroCompletoNome, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonCadastroCompletoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabelCadastroCompletoCpf)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(jFormattedTextFieldCadastroCompletoCpf)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonCadastroRapido)
                    .addComponent(jRadioButtonCadastroCompleto))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroRapidoNome)
                    .addComponent(jLabelCadastroCompletoNome)
                    .addComponent(jLabelCadastroCompletoCpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCadastroRapidoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCadastroCompletoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldCadastroCompletoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadastroRapidoRenda)
                    .addComponent(jLabelCadastroCompletoSigno)
                    .addComponent(jLabelCadastroCompletoRenda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCadastroRapidoRenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCadastroCompletoSigno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCadastroCompletoRenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxCadastroCompletoTemPet))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButtonCadastroRapidoSalvar))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCadastroCompletoSalvar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonCadastroRapidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCadastroRapidoActionPerformed
        habilitarModoCadastroRapido();
    }//GEN-LAST:event_jRadioButtonCadastroRapidoActionPerformed

    private void jRadioButtonCadastroCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCadastroCompletoActionPerformed
        habilitarModoCadastroCompleto();
    }//GEN-LAST:event_jRadioButtonCadastroCompletoActionPerformed

    private void jButtonCadastroRapidoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroRapidoSalvarActionPerformed
        var nome = jTextFieldCadastroRapidoNome.getText();
        var renda = Double.parseDouble(jTextFieldCadastroRapidoRenda.getText());
        
        var pessoa = new Pessoa(nome, renda);
        
        // armazenar esta pessoa na lista de pessoas
        pessoaServico.adicionar(pessoa);
        
        // listar as pessoas no JTable
        listarPessoas();
    }//GEN-LAST:event_jButtonCadastroRapidoSalvarActionPerformed

    private void jButtonCadastroCompletoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroCompletoSalvarActionPerformed
        var nome = jTextFieldCadastroCompletoNome.getText();
        var renda = Double.parseDouble(jTextFieldCadastroCompletoRenda.getText());
        var possuiPet = jCheckBoxCadastroCompletoTemPet.isSelected();
        var signo = jComboBoxCadastroCompletoSigno.getSelectedItem().toString();
        var cpf = jFormattedTextFieldCadastroCompletoCpf.getValue().toString();
        
        var pessoa = new Pessoa(nome, renda, cpf, signo, possuiPet);
        // Armazenar os dados da pessoa cadastrada
        pessoaServico.adicionar(pessoa);
        
        // listar os dados das pessoas cadastradas
        listarPessoas();
    }//GEN-LAST:event_jButtonCadastroCompletoSalvarActionPerformed

    private void habilitarModoCadastroRapido(){
        // Desabilitar campos do cadastro completo
        jTextFieldCadastroCompletoNome.setEnabled(false);
        jTextFieldCadastroCompletoRenda.setEnabled(false);
        jCheckBoxCadastroCompletoTemPet.setEnabled(false);
        jComboBoxCadastroCompletoSigno.setEnabled(false);
        jFormattedTextFieldCadastroCompletoCpf.setEnabled(false);
        jButtonCadastroCompletoSalvar.setEnabled(false);
        
        // Habilitar campos do cadastro rápido
        jTextFieldCadastroRapidoNome.setEnabled(true);
        jTextFieldCadastroRapidoRenda.setEnabled(true);
        jButtonCadastroRapidoSalvar.setEnabled(true);
    }
    
    private void habilitarModoCadastroCompleto(){
        // Desabilitar campos do cadastro rápido
        jTextFieldCadastroRapidoNome.setEnabled(false);
        jTextFieldCadastroRapidoRenda.setEnabled(false);
        jButtonCadastroRapidoSalvar.setEnabled(false);
        
        // Habilitar campos do cadastro completo
        jTextFieldCadastroCompletoNome.setEnabled(true);
        jTextFieldCadastroCompletoRenda.setEnabled(true);
        jCheckBoxCadastroCompletoTemPet.setEnabled(true);
        jComboBoxCadastroCompletoSigno.setEnabled(true);
        jFormattedTextFieldCadastroCompletoCpf.setEnabled(true);
        jButtonCadastroCompletoSalvar.setEnabled(true);
    }
    
    private void listarPessoas(){
        var pessoas = pessoaServico.obterTodasPessoas();
        
        // For para percorrer a lista de pessoas e adicionar na tabela
        // for (int i = 0; i < pessoas.size(); i++) {
            // Obter o objeto da pessoa que está armazenado na lista de pessoas;
        //    var pessoa = pessoas.get(i);
        //}
        
        var modelo = (DefaultTableModel) jTable1.getModel();
        // Limpar a tabela
        modelo.setRowCount(0);
        
        // foreach: utilizado para percorrer listas, onde o indice 
        // atual não é importante
        for(var pessoa : pessoas){
            // Adicionar uma nova linha na tabela com as informações da pessoa
            modelo.addRow(new Object[]{
                pessoa.getNome(),
                pessoa.getCpf(),
                pessoa.getRenda(),
                pessoa.isPossuiPet(),
                pessoa.getSigno()
            });
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PessoaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PessoaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PessoaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PessoaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PessoaJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupTipoCadastro;
    private javax.swing.JButton jButtonCadastroCompletoSalvar;
    private javax.swing.JButton jButtonCadastroRapidoSalvar;
    private javax.swing.JCheckBox jCheckBoxCadastroCompletoTemPet;
    private javax.swing.JComboBox<String> jComboBoxCadastroCompletoSigno;
    private javax.swing.JFormattedTextField jFormattedTextFieldCadastroCompletoCpf;
    private javax.swing.JLabel jLabelCadastroCompletoCpf;
    private javax.swing.JLabel jLabelCadastroCompletoNome;
    private javax.swing.JLabel jLabelCadastroCompletoRenda;
    private javax.swing.JLabel jLabelCadastroCompletoSigno;
    private javax.swing.JLabel jLabelCadastroRapidoNome;
    private javax.swing.JLabel jLabelCadastroRapidoRenda;
    private javax.swing.JRadioButton jRadioButtonCadastroCompleto;
    private javax.swing.JRadioButton jRadioButtonCadastroRapido;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCadastroCompletoNome;
    private javax.swing.JTextField jTextFieldCadastroCompletoRenda;
    private javax.swing.JTextField jTextFieldCadastroRapidoNome;
    private javax.swing.JTextField jTextFieldCadastroRapidoRenda;
    // End of variables declaration//GEN-END:variables
}
